spring: 
  profiles: 
  active: 
  - dev
  
---
#123453
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-sgf-dev
   
---   
  
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-sgf-test
